import { useEffect, useState } from "react";
import { Alert, Button, Input, Label } from "reactstrap";
import PageShell from "@/components/salon/PageShell";
import { salonApi } from "@/services/salonApi";
import { formatMoney, labelize } from "@/utils/salonFormat";

const initial={staffId:"",baseSalary:"",salaryType:"MONTHLY",workingDaysPerMonth:26,paidLeavesAllowed:0,lateGraceMinutes:10,latePenaltyType:"NONE",latePenaltyAmount:0,serviceCommissionPercentage:0,serviceMinimumWorkThreshold:0,retailCommissionPercentage:0,retailMinimumSalesThreshold:0,effectiveFrom:new Date().toISOString().slice(0,10)};
const SalaryConfig=()=>{
  const [staff,setStaff]=useState([]),[form,setForm]=useState(initial),[active,setActive]=useState(null),[error,setError]=useState("");
  useEffect(()=>{salonApi.staff.list().then(x=>setStaff(x.data||[])).catch(e=>setError(e.message));},[]);
  const select=async(id)=>{setForm({...form,staffId:id});setActive(null);if(!id)return;try{const r=await salonApi.salaryConfigs.active(id);setActive(r.data);setForm({...form,...r.data,staffId:id,effectiveFrom:new Date(r.data.effectiveFrom).toISOString().slice(0,10)});}catch(e){if(e.status!==404)setError(e.message);}};
  const save=async()=>{try{setError("");const body={...form,baseSalary:Number(form.baseSalary),workingDaysPerMonth:Number(form.workingDaysPerMonth),paidLeavesAllowed:Number(form.paidLeavesAllowed),lateGraceMinutes:Number(form.lateGraceMinutes),latePenaltyAmount:Number(form.latePenaltyAmount),serviceCommissionPercentage:Number(form.serviceCommissionPercentage),serviceMinimumWorkThreshold:Number(form.serviceMinimumWorkThreshold),retailCommissionPercentage:Number(form.retailCommissionPercentage),retailMinimumSalesThreshold:Number(form.retailMinimumSalesThreshold)};const r=active?await salonApi.salaryConfigs.update(active.id,body):await salonApi.salaryConfigs.create(form.staffId,body);setActive(r.data);}catch(e){setError(e.message);}};
  const field=(name,label,type="number")=><div className="col-md-3"><Label>{label}</Label><Input type={type} value={form[name]??""} onChange={e=>setForm({...form,[name]:e.target.value})}/></div>;
  return <PageShell title="Salary Config" description="Effective-dated salary, penalty, and commission rules.">{error&&<Alert color="danger">{error}</Alert>}<div className="card card-bordered"><div className="card-inner row g-3"><div className="col-md-4"><Label>Staff</Label><Input type="select" value={form.staffId} onChange={e=>select(e.target.value)}><option value="">Select staff</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Input></div>{field("baseSalary","Base salary")}{field("workingDaysPerMonth","Working days")}{field("paidLeavesAllowed","Paid leaves allowed")}
  <div className="col-md-3"><Label>Salary type</Label><Input type="select" value={form.salaryType} onChange={e=>setForm({...form,salaryType:e.target.value})}>{["MONTHLY","DAILY"].map(x=><option key={x}>{labelize(x)}</option>)}</Input></div>{field("lateGraceMinutes","Late grace (minutes)")}<div className="col-md-3"><Label>Late penalty</Label><Input type="select" value={form.latePenaltyType} onChange={e=>setForm({...form,latePenaltyType:e.target.value})}>{["NONE","FIXED_PER_LATE_DAY","PER_LATE_MINUTE"].map(x=><option key={x}>{labelize(x)}</option>)}</Input></div>{field("latePenaltyAmount","Penalty amount")}{field("serviceCommissionPercentage","Service commission %")}{field("serviceMinimumWorkThreshold","Service threshold")}{field("retailCommissionPercentage","Retail commission %")}{field("retailMinimumSalesThreshold","Retail threshold")}{field("effectiveFrom","Effective from","date")}<div className="col-12"><Button color="primary" disabled={!form.staffId} onClick={save}>{active?"Update configuration":"Create configuration"}</Button>{active&&<span className="ms-3 text-soft">Active base: {formatMoney(active.baseSalary)}</span>}</div></div></div></PageShell>;
};
export default SalaryConfig;
